services:
  php-fpm:
    image: php:8.4-fpm-alpine
    volumes:
      - ./app:/var/www/html

  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
